/**
 * The runbook generator.
 *
 * This is the deliverable. Every failure worth catching in this architecture
 * came from a dashboard or a DNS record, not from code — so the instructions
 * for those steps are the product, and the code that emits them is packaging.
 *
 * Four rules govern everything below, and a section that breaks one is a bug:
 *
 *  1. **Exact navigation paths.** "Vercel → thing → Settings → Deployment
 *     Protection → Vercel Authentication → Require Log In → off → Save", not
 *     "disable deployment protection".
 *
 *  2. **Real values, already substituted.** The reader must never have to
 *     translate a placeholder into their own domain. The one exception is a
 *     value that genuinely cannot be predicted — the CNAME target is
 *     account-specific — and those say so loudly rather than guessing.
 *
 *  3. **A verification after every step, with the expected output stated.**
 *     Not "check that it worked".
 *
 *  4. **What it looks like when it goes wrong, inline.** The grey-cloud step
 *     says what a proxied record produces, next to the step, not in an
 *     appendix the reader reaches after an hour.
 */

/** `/thing` → `thing`; `/a/b` → `a-b`. Used for suggested names. */
export function slug(basePath) {
  return basePath.replace(/^\/+/, "").replace(/\//g, "-");
}

export function renderRunbook(config) {
  const {
    origin,
    basePath,
    publicUrl,
    subdomain,
    childProject,
    apexProject,
    unlisted,
    wayBack,
  } = config;

  const apexHost = new URL(origin).host;
  const recordName = subdomain.replace(`.${apexHost}`, "");
  const childUrl = `https://${subdomain}${basePath}`;

  const sections = [
    header({ publicUrl, subdomain, basePath, apexHost }),
    beforeYouStart({ childProject, apexProject, apexHost }),
    stepProtection({ childProject }),
    stepAddDomain({ childProject, subdomain }),
    stepDns({ recordName, subdomain, apexHost }),
    stepVerifyDns({ subdomain, childUrl, basePath, publicUrl }),
    stepChildConfig({ basePath, origin, publicUrl, unlisted }),
    stepVerifyChild({ childUrl, basePath, subdomain }),
    stepApexRewrites({ apexProject, basePath, subdomain, apexHost }),
    stepVerifyProxy({ publicUrl, subdomain, unlisted, basePath, apexHost }),
    wayBack?.enabled ? stepWayBack({ basePath, publicUrl, wayBack, apexHost }) : null,
    stepRollback({ basePath, subdomain, publicUrl }),
    troubleshooting({ basePath, publicUrl, apexHost, wayBack }),
  ];

  return `${sections.filter(Boolean).join("\n\n---\n\n")}\n`;
}

function header({ publicUrl, subdomain, basePath, apexHost }) {
  return `# Runbook — serving an app at ${publicUrl}

Generated by \`annex-as-subpath\`. Every value below is already filled in for
this project; nothing here is a placeholder except where a step says to copy a
value off a screen.

| | |
| --- | --- |
| Public URL (the advertised one) | \`${publicUrl}\` |
| Apex domain | \`${apexHost}\` |
| Child \`basePath\` | \`${basePath}\` |
| Rewrite target subdomain | \`${subdomain}\` |

**Follow the steps in order.** The order is not stylistic: each step rules
something out so the next one's failure means what it says. Reversed, the first
symptom you see points at the wrong cause and you debug the wrong system.

**You cannot test any of this on a local dev server.** \`vercel.json\` rewrites
are a platform feature, so \`${basePath}\` returns 404 locally no matter what is
configured. This is the single most likely thing to send you chasing a problem
that does not exist. Use \`vercel dev\` on the apex, a preview deployment, or
production.`;
}

function beforeYouStart({ childProject, apexProject, apexHost }) {
  return `## Before you start

You need:

- Vercel access to the child project (\`${childProject}\`).
- Vercel access to the apex project (\`${apexProject}\`).
- DNS access for \`${apexHost}\`.
- Write access to both repos.

Two Vercel projects, two repos, one domain. The apex owns the domain and
rewrites a path to the child; the child knows nothing about the apex except its
own \`basePath\`.`;
}

function stepProtection({ childProject }) {
  return `## 1. Turn off Deployment Protection on the child

**Vercel → \`${childProject}\` → Settings → Deployment Protection → Vercel
Authentication → Require Log In → off (Production) → Save.**

**First, not last.** Vercel Authentication intercepts the apex's proxied
request too, not just direct visits. Leave it on and every check below returns
an SSO login page — so you cannot tell protection from a DNS fault, a bad
rewrite, or a missing \`basePath\`. One setting makes all four look identical.

Protection Bypass for Automation cannot rescue this: \`vercel.json\` rewrites
cannot inject headers, so there is nowhere to put the bypass token.

**Verify:** open the project's current production deployment URL in a private
window. You should see the app, or a 404 from the app — **not** a Vercel login
screen. If you see a login screen, the setting did not save, or it is set on
Preview but not Production.`;
}

function stepAddDomain({ childProject, subdomain }) {
  return `## 2. Add the subdomain to the child project

**Vercel → \`${childProject}\` → Settings → Domains → Add** →

\`\`\`
${subdomain}
\`\`\`

Why a subdomain you own rather than the generated \`*.vercel.app\` alias: the
generated alias changes if the project or the account is ever renamed, and it
is the rewrite target, so the apex would break silently. Nothing but the apex
rewrite ever requests this hostname. The advertised URL does not change.

**Vercel now shows you a CNAME target.** It has the shape
\`a1b2c3d4e5f6a7b8.vercel-dns-0NN.com\` — that one is invented, yours will not
match it.

> **Copy that value off this screen. It is account-specific.**
> It cannot be predicted, and it is not the one in this runbook — the example
> above is somebody else's. A guessed target fails in a way that looks like a
> DNS propagation delay, so you wait an hour before doubting it.

**Verify:** the domain is listed, with a warning that configuration is needed.
That warning is expected until step 3.`;
}

function stepDns({ recordName, subdomain, apexHost }) {
  return `## 3. Create the DNS record

In your DNS provider for \`${apexHost}\`, create:

| Field | Value |
| --- | --- |
| Type | \`CNAME\` |
| Name | \`${recordName}\` |
| Target | **the value you copied in step 2** — account-specific, not guessable |
| Proxy status | **DNS only** (grey cloud, *not* orange) |
| TTL | Auto |

**Proxy status is the one that bites.** Vercel issues and renews the TLS
certificate for \`${subdomain}\` and validates ownership by seeing the request
reach its own edge. With Cloudflare terminating TLS in front, that validation
fails — or, worse, succeeds once and then silently stops renewing months later,
long after you have stopped associating the outage with this checkbox.

On Cloudflare's "Flexible" SSL mode you also get a redirect loop.

What a proxied record produces, so you recognise it: \`cf-ray\` and
\`cf-cache-status\` headers on the response, a certificate that never issues, and
a TTL field that stays greyed out. **TTL is not editable while proxied** — if
you cannot set TTL, the cloud is still orange.

Not on Cloudflare? The rule generalises: this record must resolve straight to
Vercel, with no CDN or proxy in front terminating TLS.

**Then wait** for Vercel to mark the domain **Valid** and issue the
certificate. Usually under a minute; occasionally longer.`;
}

function stepVerifyDns({ subdomain, childUrl, basePath, publicUrl }) {
  return `## 4. Verify DNS and TLS

\`\`\`bash
dig +short ${subdomain} CNAME
\`\`\`

Expected: the Vercel target from step 2, ending in a dot. An **empty result**
means the record does not exist yet or is proxied — Cloudflare flattens a
proxied CNAME into A records, so \`dig\` for a CNAME returns nothing. A set of
**IP addresses** instead means the same thing.

\`\`\`bash
curl -sSI ${childUrl} | grep -iE '^HTTP|^cf-'
\`\`\`

Expected: \`HTTP/2 200\` and **no \`cf-\` lines at all**. Any \`cf-ray\` or
\`cf-cache-status\` means the proxy is still on — go back to step 3.

A TLS error here means the certificate has not issued. Wait, then re-check that
the record is grey-clouded; those are the only two causes.

Note the app answers at \`${childUrl}\`, not at the bare subdomain — \`basePath\`
applies on this host too. The bare root redirects to \`${publicUrl}\`. That looks
odd and is correct; \`${basePath}\` is the app's path everywhere it is served.`;
}

function stepChildConfig({ basePath, origin, publicUrl, unlisted }) {
  const robotsBlock = unlisted
    ? `  // Unlisted, not private: anyone with the link gets in with zero friction,
  // but it stays out of search results. Leave robots.txt permissive —
  // disallowing this path there would advertise it, and a crawler blocked
  // from fetching the page never sees this tag anyway.
  robots: { index: false, follow: false },
`
    : "";

  return `## 5. Configure the child app

Three files. Do this before deploying — a deploy without \`basePath\` produces
the most confusing symptom in this whole system.

**\`src/lib/base-path.ts\`** — one source of truth, imported by the config and
the metadata so neither is written out by hand:

\`\`\`ts
export const BASE_PATH = "${basePath}";
export const SITE_URL = "${origin}";
export const PUBLIC_URL = \`\${SITE_URL}\${BASE_PATH}\`;

/**
 * Prefix a path to a file in \`public/\` with the deployment basePath.
 *
 * next/link and the router add basePath on their own — this is for the places
 * that don't: next/image src, plain <img>/<link>/<video>, fetches of static
 * files, and metadata URLs.
 *
 *   assetPath("/logo.svg") // -> "${basePath}/logo.svg"
 */
export function assetPath(path: \`/\${string}\`): string {
  return \`\${BASE_PATH}\${path}\`;
}
\`\`\`

**\`next.config.ts\`**:

\`\`\`ts
import type { NextConfig } from "next";
import { BASE_PATH, PUBLIC_URL } from "./src/lib/base-path";

const nextConfig: NextConfig = {
  basePath: BASE_PATH,
  async redirects() {
    return [
      {
        // Bare root ONLY. Rescues anyone who lands on a deployment host
        // directly by sending them to the canonical URL.
        //
        // Safe because with basePath set the proxy never requests "/".
        // Do NOT broaden this to ${basePath}/* : the apex would receive the
        // 3xx, pass it to the browser, and the browser would come back
        // through the apex — an infinite loop on the canonical URL.
        source: "/",
        destination: PUBLIC_URL,
        basePath: false,  // without this, Next prefixes the source with ${basePath}
        permanent: false, // 301s cache hard in browsers
      },
    ];
  },
};

export default nextConfig;
\`\`\`

**Root layout metadata**:

\`\`\`ts
import { PUBLIC_URL } from "@/lib/base-path";

export const metadata: Metadata = {
  // Resolves relative metadata URLs against the public URL, not the
  // deployment host the app happens to be served from.
  metadataBase: new URL(PUBLIC_URL),
  // Absolute on purpose. A relative "/" resolves to PUBLIC_URL *with* a
  // trailing slash, and Next 308s that back to the unslashed form — a
  // canonical tag naming a URL that redirects.
  alternates: { canonical: PUBLIC_URL },
${robotsBlock}};
\`\`\`

**Then audit for root-absolute paths.** Search the source for \`"/\` inside
\`src\`, \`href\`, and \`url()\`. Anything pointing at a file in \`public/\` needs
\`assetPath()\`. \`basePath\` does **not** prefix \`public/\` — a raw
\`/logo.svg\` works locally and 404s in production, and it is the one failure
that survives every check that only looks at the page HTML.

**Verify:** \`npm run build\` succeeds, then \`npm run dev\` and open
\`http://localhost:3000${basePath}\`. \`/\` redirecting away is correct.`;
}

function stepVerifyChild({ childUrl, basePath, subdomain }) {
  return `## 6. Deploy the child and verify it standalone

Deploy to production, then check **on \`${childUrl}\`** — before involving the
apex at all. Anything broken here is broken for a reason that has nothing to do
with the proxy, and finding it now saves you from debugging the wrong system.

- [ ] Renders fully: styles, fonts, layout. Not just text on white.
- [ ] **Network tab, filtered to \`_next\` — every request under
      \`${basePath}/_next/…\`, none at the root.** *This is the check that
      matters.* When it is broken the HTML still arrives, so the page looks
      perfect here and shatters behind the proxy.
- [ ] Deep links survive a hard reload, not only client-side navigation.
- [ ] No console errors, no hydration warnings.
- [ ] Private window: no SSO screen. If there is one, step 1 did not take.

\`\`\`bash
curl -s ${childUrl} | grep -o '/_next/[^"]*' | grep -v '^${basePath}' | head
\`\`\`

Expected: **no output.** Any line printed is an asset that will 404 behind the
apex — \`basePath\` is missing or not applied.

Fix everything here before touching the apex.`;
}

function stepApexRewrites({ apexProject, basePath, subdomain, apexHost }) {
  return `## 7. Add the rewrites to the apex

In the **apex repo** (\`${apexHost}\`), in \`vercel.json\`:

\`\`\`json
{
  "rewrites": [
    {
      "source": "${basePath}",
      "destination": "https://${subdomain}${basePath}"
    },
    {
      "source": "${basePath}/:path*",
      "destination": "https://${subdomain}${basePath}/:path*"
    }
  ]
}
\`\`\`

**Both rules.** With only the wildcard, \`${basePath}\` itself 404s while
\`${basePath}/anything\` works — a symptom that reads like a routing bug in the
child app and is not.

Rewrites, not redirects: the browser only ever sees \`${apexHost}\`.

If \`vercel.json\` already exists, merge these into the existing \`rewrites\`
array rather than replacing the file.

Deploy the apex. **Vercel → \`${apexProject}\`** — and note that a local dev
server ignores \`vercel.json\` entirely, so a local check here proves nothing.

**Verify:** the apex deployment finished, and its build log shows no
\`vercel.json\` parse error. A malformed \`vercel.json\` fails the build rather
than deploying a broken config, which is the one merciful part of this.`;
}

function stepVerifyProxy({ publicUrl, subdomain, unlisted, basePath, apexHost }) {
  const flags = [`--subdomain ${subdomain}`, unlisted ? "--unlisted" : "--indexed"].join(" ");

  return `## 8. Verify the whole chain

\`\`\`bash
pnpm dlx annex-as-subpath doctor ${publicUrl} ${flags}
\`\`\`

Expected: every check passes, exit code 0. Each failure prints what to do about
it. Work top-down — a failure high in the list causes the ones below it, and
checks that would misdiagnose while it is broken report as blocked rather than
guessing.

By hand, if you prefer:

\`\`\`bash
curl -sSI ${publicUrl} | grep -iE '^HTTP|^location'
\`\`\`

Expected: \`HTTP/2 200\`, no \`location\` header. A 3xx to another host means
something redirected instead of being proxied — including the apex's own
apex/www canonicalisation, which is easy to forget you have.

Then in a browser, on \`${publicUrl}\`:

- [ ] Loads, and the address bar still reads \`${apexHost}${basePath}\`.
- [ ] Works with and without a trailing slash, without bouncing hosts.
- [ ] \`${basePath}/does-not-exist\` gives the **app's** 404, not the apex's.
- [ ] The apex's own pages still work.
- [ ] No 404s in the network tab.`;
}

function stepWayBack({ basePath, publicUrl, wayBack, apexHost }) {
  return `## 9. The way back (optional)

An unlisted page is deliberately not linked from anywhere, so a visitor who
arrives through it and then wanders to \`${apexHost}\` has no route back. This
offers them one.

The child writes a single \`sessionStorage\` key; the apex reads it and shows a
link. The contract:

\`\`\`
key:   "unlisted-entry"
value: {"label": ${JSON.stringify(wayBack.label)}, "href": "${basePath}"}
\`\`\`

\`label\` is substituted into the sentence "I believe you came here through
___", so it has to fit that grammar. \`href\` is resolved on the apex's origin,
so it must be apex-relative — never the child's own host. It equals the child's
\`basePath\` by construction, since the rewrite maps them one-to-one.

**It is \`sessionStorage\`, not a cookie.** Client-only, scoped per origin, dies
with the tab. No cookies, no identifiers, nothing sent anywhere. Do not make it
more persistent — it is a courtesy, not analytics.

Write it as an **inline script in a server component**, not a \`useEffect\`, so
it runs before hydration and needs no \`"use client"\`. Wrap the storage call in
\`try/catch\`: Safari private mode throws on access, and a courtesy feature must
never break the page.

**Verify:** visit \`${publicUrl}\`, then go to \`https://${apexHost}\` in the same
tab. The link should appear.

If it does not, check this first: **you must arrive through \`${apexHost}\`.**
\`sessionStorage\` is per-origin, so visiting the child's own host writes to
storage the apex cannot read. That is expected behaviour, not a bug, and it is
the cause almost every time.

With JavaScript disabled the element must stay hidden — never an empty or
unstyled banner.`;
}

function stepRollback({ basePath, subdomain, publicUrl }) {
  return `## 10. Rollback and monitoring

**Rollback:** point both \`destination\` values in the apex's \`vercel.json\` back
to the child's \`*.vercel.app\` alias and redeploy the apex. Two minutes. The
alias stays reachable throughout, so it is always available as a manual
fallback.

A *second* rewrite rule is not a fallback. \`vercel.json\` rewrites are static
path matching with no health checks — the same \`source\` twice means the first
wins and the second is dead config. Do not add one.

**Monitoring:** put an uptime check on \`${publicUrl}\`. The failure that
actually costs something here is not downtime, it is silence — the path
breaking weeks after you sent the link, when nobody is looking. Nothing in the
configuration catches that, and the certificate on \`${subdomain}\` is the most
likely thing to expire quietly.

Re-running the doctor on a schedule covers the same ground:

\`\`\`bash
pnpm dlx annex-as-subpath doctor ${publicUrl}
\`\`\``;
}

function troubleshooting({ basePath, publicUrl, apexHost, wayBack }) {
  // A table row pointing at a step the reader does not have is worse than no
  // row: it sends them looking for a section that was never generated.
  const wayBackRow = wayBack?.enabled
    ? "| Way-back link never appears | Arrived on the child's host; storage is per-origin | 9 |\n"
    : "";

  return `## Symptom → cause

| Symptom | Almost certainly | Step |
| --- | --- | --- |
| Vercel SSO / login page | Deployment Protection still on for Production | 1 |
| \`cf-ray\` header on the subdomain | DNS record still proxied — needs grey cloud | 3 |
| Certificate invalid or never issues | Same: Vercel cannot validate through the proxy | 3 |
| \`dig CNAME\` returns nothing, or returns IPs | Same: a proxied CNAME is flattened to A records | 3 |
| DNS looks right but the host is unreachable | Guessed CNAME target instead of copying it | 2 |
| HTML loads, page blank, 404s on \`/_next/*\` | \`basePath\` missing | 5 |
| One image 404s, everything else fine | A \`public/\` file referenced without \`assetPath()\` | 5 |
| \`ERR_TOO_MANY_REDIRECTS\` | A redirect covering \`${basePath}/*\`; only bare \`/\` may redirect | 5 |
| Address bar flips to another host | A 3xx passed through the proxy, or apex/www canonicalisation | 7 |
| Canonical tag names a URL that redirects | Relative canonical, or the apex canonicalises to \`www\` | 5 |
| \`${basePath}\` 404s but \`${basePath}/x\` works | The non-wildcard rewrite rule is missing | 7 |
| Everything 404s, but only locally | Expected — a local dev server ignores \`vercel.json\` | — |
${wayBackRow}
## What this runbook does not cover

Choosing whether the apex itself is proxied. It does not need to change: the
rewrite is executed by Vercel, and proxy status is per-record, so a proxied
apex alongside a DNS-only subdomain is a normal mixed setup. If the apex is
proxied, Cloudflare SSL/TLS must be **Full (strict)**.

\`\`\`bash
curl -sSI ${publicUrl} | grep -iE 'server|cf-ray'
\`\`\`

\`cf-ray\` or \`server: cloudflare\` means \`${apexHost}\` is proxied.`;
}
